CREATE TABLE IF NOT EXISTS operation_records (
  id SERIAL PRIMARY KEY,
  module_name VARCHAR(120) NOT NULL,
  owner_name VARCHAR(80) NOT NULL,
  status VARCHAR(40) NOT NULL,
  metric VARCHAR(40) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO operation_records (module_name, owner_name, status, metric)
VALUES ('剧本库与DM管理', '运营组', 'ready', '100%');

CREATE TABLE IF NOT EXISTS sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(120) NOT NULL,
  script_name VARCHAR(120) NOT NULL,
  dm_name VARCHAR(80) NOT NULL,
  start_time VARCHAR(40) NOT NULL,
  capacity INT NOT NULL,
  last_event VARCHAR(255) NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS registrations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id BIGINT NOT NULL REFERENCES sessions (id),
  player_name VARCHAR(80) NOT NULL,
  status VARCHAR(16) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_registration_player UNIQUE (session_id, player_name)
);

CREATE INDEX IF NOT EXISTS idx_registrations_session_status ON registrations (session_id, status, id);

INSERT INTO sessions (title, script_name, dm_name, start_time, capacity, last_event)
VALUES
  ('周五晚场 · 硬核推理', '年轮', '老K', '今天 19:00', 6, '暂无补位记录'),
  ('周六下午场 · 情感沉浸', '金陵有座东君书院', '阿离', '明天 14:00', 7, '暂无补位记录'),
  ('周六晚场 · 欢乐机制', '来电', '北辰', '明天 19:30', 8, '暂无补位记录');

INSERT INTO registrations (session_id, player_name, status)
VALUES
  (1, '林晚', 'SEATED'),
  (1, '周野', 'SEATED'),
  (1, '苏离', 'SEATED'),
  (1, '陈默', 'SEATED');
