-- 本地 H2 内存库建表脚本，与 database/init.sql（PostgreSQL）保持一致
CREATE TABLE IF NOT EXISTS sessions (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title           VARCHAR(120) NOT NULL,
  start_time      TIMESTAMP NOT NULL,
  capacity        INTEGER NOT NULL CHECK (capacity > 0),
  last_promoted_player VARCHAR(80),
  last_promoted_at     TIMESTAMP,
  last_promotion_note  VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS session_registrations (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id   INTEGER NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  player_name  VARCHAR(80) NOT NULL,
  status       VARCHAR(16) NOT NULL,
  wait_position INTEGER,
  created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (session_id, player_name)
);

CREATE INDEX IF NOT EXISTS idx_registrations_session_waiting
  ON session_registrations (session_id, status, id);
