CREATE TABLE IF NOT EXISTS sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(120) NOT NULL,
  script_name VARCHAR(120) NOT NULL,
  dm_name VARCHAR(80) NOT NULL,
  start_time VARCHAR(40) NOT NULL,
  capacity INT NOT NULL,
  last_event VARCHAR(255) NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS registrations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id BIGINT NOT NULL REFERENCES sessions (id),
  player_name VARCHAR(80) NOT NULL,
  status VARCHAR(16) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_registration_player UNIQUE (session_id, player_name)
);

CREATE INDEX IF NOT EXISTS idx_registrations_session_status ON registrations (session_id, status, id);
